headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]

[build]
publish = "C:\\Users\\Acer\\Documents\\Default Project\\ai-karyawan-saas\\.next"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,GEMINI_API_KEY"
SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache"
NEXT_PUBLIC_SUPABASE_URL = "https://ajogenjwhgxqmkqepvyz.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqb2dlbmp3aGd4cW1rcWVwdnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk1NTYwNzMsImV4cCI6MjEwNTEzMjA3M30.bBmd5nrBiVIIoFJMj-0ctxH6dVv8qO0f-4FJJtK1OxQ"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image"
to = "/.netlify/images"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]